# Generated by Django 5.0.1 on 2024-02-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_mpin_for_login_customuser_address_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mpin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking_app.mpin_for_login'),
        ),
    ]
