# Generated by Django 5.0.1 on 2024-02-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0003_customuser_mpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mpin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Mpin_for_login',
        ),
    ]
