# Generated by Django 5.0.1 on 2024-02-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0005_customuser_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ifsc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
