# Generated by Django 5.0.1 on 2024-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0006_remove_customuser_address_customuser_ifsc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ifsc',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
