# Generated by Django 5.0.1 on 2024-02-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0007_remove_customuser_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ifsc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
