# Generated by Django 5.0.1 on 2024-02-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0008_customuser_account_number_customuser_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
