# Generated by Django 5.0.1 on 2024-02-25 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0010_fund_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund_transfer',
            name='id',
        ),
        migrations.AlterField(
            model_name='fund_transfer',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
