# Generated by Django 5.0.1 on 2024-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0011_remove_fund_transfer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_transfer',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
