# Generated by Django 5.0.1 on 2024-02-25 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0012_fund_transfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_transfer',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fund_transfer',
            name='ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
