# Generated by Django 5.0.1 on 2024-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0014_remove_fund_transfer_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_transfer',
            name='mpin',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
