# Generated by Django 5.0.1 on 2024-02-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0015_fund_transfer_mpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_transfer',
            name='fund_receiving_other_bank_user',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
