# Generated by Django 5.0.1 on 2024-02-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0017_fund_transfer_bill_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_transfer',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fund_transfer',
            name='is_debit',
            field=models.BooleanField(default=False),
        ),
    ]
