# Generated by Django 5.0.1 on 2024-02-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0019_remove_fund_transfer_is_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund_transfer',
            old_name='date_of_trasaction',
            new_name='date_of_transaction',
        ),
    ]
